[package]
name = "survey"
version = "0.1.1"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
description = "NixOS advisory survey (used to feed vulnerability roundups)"
keywords = ["security"]

[dependencies]
clap = { version = "2.32", features = ["wrap_help", "color"] }
colored = "1.6"
failure = "0.1"
failure_derive = "0.1"
lazy_static = "1.2"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
structopt-derive = "0.2"
subprocess = "0.1.17"

[dev-dependencies]
tempdir = "0.3.7"

[profile.release]
panic = "abort"
