[package]
name = "survey"
version = "0.5.0"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
description = "NixOS advisory survey (used to feed vulnerability roundups)"
keywords = ["security"]
edition = "2018"

[dependencies]
clap = { version = "2.33", features = ["wrap_help", "color"] }
colored = "1.8"
dotenv = "0.14"
float-ord = "0.2"
futures = "0.1"
git2 = { version = "0.10", default-features = false }
hubcaps = "0.5"
hyper = "*"
hyper-tls = "*"
lazy_static = "1.3"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
smallstr = "0.1"
snafu = "0.5"
structopt = "0.3"
structopt-derive = "0.2"
subprocess = "0.1.17"
tokio = "0.1"

[dev-dependencies]
assert_matches = "1.3"
libflate = "0.1.25"
maplit = "1"
tar = "0.4.25"
tempdir = "0.3.7"

[profile.release]
panic = "abort"
