[package]
name = "survey"
version = "0.1.0"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
description = "NixOS vulnerability survey"

[dependencies]
clap = { version = "2.32", features = ["wrap_help"] }
failure = "0.1"
failure_derive = "0.1"
lazy_static = "1.2"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
structopt-derive = "0.2"

[profile.release]
panic = "abort"
